### ISSUE TITLE
Evaluate Java8 streams

### ISSUE THREAD

**Issue by nhuszka** [nhuszka/CollectionEvaluator#1]
Make measurements with 
- stream().forEach(...)
- parallelStream().forEach(...)

**Comment by hnandor** [comment]
Collection interface usage
- add elements with Collection's remove(...)
- remove with remove(...)

**Comment by nhuszka** [comment]
There are classes for it, for instance:
https://github.com/hnandor/CollectionEvaluator/blob/master/src/com/nhuszka/collection_evaluator/evaluator/evaluation_strategy/queue/FilterQueueStreamStrategy.java
